### ISSUE TITLE
Facet to-do list

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/tinyplot#90]
Moved from #83.

- [x] Smarter arrangements of facets (e.g., "square" window arrangements) instead of current single row default. (#91)
- [x] Smarter axes options (e.g., only print the axis ticks for the "outer" facets). (#91)
- [ ] Should we allow free axis scaling/limits for individual facets?
- [x] Extra facets.args argument to control the above three options (maybe others). (#91)
- [x] #100
- [x] If yes to the above, should we integrate formula support directly into the plot.formula method somehow... maybe via a second vertical bar, e.g. `y ~ x | by | facetrow ~ facetcol`? **Decision:** No.
- [x] Alternatively, maybe  `y ~ x | by, facet = TRUE` could treat  `by` as a facet variable and override the default grouping behaivour (distinct from `facet = "by"`, which treats them as equivalent).  **Decision:** No.
- [x] Should the larger legend `cex` be adjusted to match the smaller facet elements (or, vice versa)? (#91)
- [x] Consistent facet margins that can be adjusted by the user. (#94) 
- [x] #98
- [x] #103 

Relevant comments:

https://github.com/grantmcdermott/plot2/pull/83#issuecomment-1834663508 (@zeileis)

> Layout: In my first attempt to add both faceting and categorical variables https://github.com/grantmcdermott/plot2/pull/12, I had just added an argument mfrow so that we could set mfrow = TRUE or mfrow = c(1, 4) etc. Maybe this would be feasible for letting the users decide whether they want square layouts or not.
>
> Axes: It would be good to separate out the functions for drawing the panels and drawing the axes now. This might let us add the support for categorical variables from https://github.com/grantmcdermott/plot2/pull/12 that we had further discussed in https://github.com/grantmcdermott/plot2/issues/2. My suggestion was that there should be workhorse functions a la plot2_xclass_yclass_plottype(x, y, by, axes = TRUE, ...).
>
> From reading your description above (but not studying the code in detail), I thought that it might maybe help to have accompanying functions axis2_xlass_yclass_plottype(...) that could be inserted into the workflow for drawing the axes?

https://github.com/grantmcdermott/plot2/pull/83#issuecomment-1838775014 (@vincentarelbundock)
> Personally, I would avoid putting too much burden on the formula. Faceting does feel like a different functionality which should mostly (exclusively?) be called with its own argument. Also, focusing on the facet argument eventually allow us to do more complex things like multiple variables with a two-sided formula indicating rows and columns.
>
> The mfrow feature seems important and powerful. Is that name too generic? Will people think it does something else, like allow multiple plot2() calls? If it only applies to facet, maybe it should be facet_mfrow. I don't have a strong view...
